// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type VideoStatus string

const (
	VideoStatusUploading  VideoStatus = "uploading"
	VideoStatusProcessing VideoStatus = "processing"
	VideoStatusReady      VideoStatus = "ready"
	VideoStatusFailed     VideoStatus = "failed"
)

func (e *VideoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VideoStatus(s)
	case string:
		*e = VideoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VideoStatus: %T", src)
	}
	return nil
}

type NullVideoStatus struct {
	VideoStatus VideoStatus
	Valid       bool // Valid is true if VideoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVideoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VideoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VideoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVideoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VideoStatus), nil
}

type Video struct {
	ID             uuid.UUID
	Title          string
	Status         VideoStatus
	Duration       *float64
	Width          *int32
	Height         *int32
	SizeBytes      *int64
	MasterPlaylist *string
	Thumbnail      *string
	SourceBucket   string
	SourceKey      string
	ErrorMessage   *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
