// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (id, title, source_bucket, source_key)
VALUES ($1, $2, $3, $4)
RETURNING id, title, status, duration, width, height, size_bytes, master_playlist, thumbnail, source_bucket, source_key, error_message, created_at, updated_at
`

type CreateVideoParams struct {
	ID           uuid.UUID
	Title        string
	SourceBucket string
	SourceKey    string
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.ID,
		arg.Title,
		arg.SourceBucket,
		arg.SourceKey,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.MasterPlaylist,
		&i.Thumbnail,
		&i.SourceBucket,
		&i.SourceKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, title, status, duration, width, height, size_bytes, master_playlist, thumbnail, source_bucket, source_key, error_message, created_at, updated_at FROM videos WHERE id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.MasterPlaylist,
		&i.Thumbnail,
		&i.SourceBucket,
		&i.SourceKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFailed = `-- name: MarkFailed :one
UPDATE videos
SET status = 'failed', error_message = $2
WHERE id = $1
RETURNING id, title, status, duration, width, height, size_bytes, master_playlist, thumbnail, source_bucket, source_key, error_message, created_at, updated_at
`

type MarkFailedParams struct {
	ID           uuid.UUID
	ErrorMessage *string
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) (Video, error) {
	row := q.db.QueryRow(ctx, markFailed, arg.ID, arg.ErrorMessage)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.MasterPlaylist,
		&i.Thumbnail,
		&i.SourceBucket,
		&i.SourceKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markProcessing = `-- name: MarkProcessing :one
UPDATE videos
SET status = 'processing'
WHERE id = $1
RETURNING id, title, status, duration, width, height, size_bytes, master_playlist, thumbnail, source_bucket, source_key, error_message, created_at, updated_at
`

func (q *Queries) MarkProcessing(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, markProcessing, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.MasterPlaylist,
		&i.Thumbnail,
		&i.SourceBucket,
		&i.SourceKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markReady = `-- name: MarkReady :one
UPDATE videos
SET status = 'ready',
    duration = $2,
    width = $3,
    height = $4,
    size_bytes = $5,
    master_playlist = $6,
    thumbnail = $7,
    error_message = NULL
WHERE id = $1
RETURNING id, title, status, duration, width, height, size_bytes, master_playlist, thumbnail, source_bucket, source_key, error_message, created_at, updated_at
`

type MarkReadyParams struct {
	ID             uuid.UUID
	Duration       *float64
	Width          *int32
	Height         *int32
	SizeBytes      *int64
	MasterPlaylist *string
	Thumbnail      *string
}

func (q *Queries) MarkReady(ctx context.Context, arg MarkReadyParams) (Video, error) {
	row := q.db.QueryRow(ctx, markReady,
		arg.ID,
		arg.Duration,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.MasterPlaylist,
		arg.Thumbnail,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.MasterPlaylist,
		&i.Thumbnail,
		&i.SourceBucket,
		&i.SourceKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
