// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countVideos = `-- name: CountVideos :one
SELECT COUNT(*) FROM videos
`

func (q *Queries) CountVideos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countVideos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (id, title, source_bucket, source_key)
VALUES ($1, $2, $3, $4)
RETURNING id, title, status, duration, width, height, size_bytes, master_playlist, thumbnail, source_bucket, source_key, error_message, created_at, updated_at
`

type CreateVideoParams struct {
	ID           uuid.UUID
	Title        string
	SourceBucket string
	SourceKey    string
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.ID,
		arg.Title,
		arg.SourceBucket,
		arg.SourceKey,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.MasterPlaylist,
		&i.Thumbnail,
		&i.SourceBucket,
		&i.SourceKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVideo = `-- name: DeleteVideo :one
DELETE FROM videos WHERE id = $1 RETURNING id, title, status, duration, width, height, size_bytes, master_playlist, thumbnail, source_bucket, source_key, error_message, created_at, updated_at
`

func (q *Queries) DeleteVideo(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, deleteVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.MasterPlaylist,
		&i.Thumbnail,
		&i.SourceBucket,
		&i.SourceKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, title, status, duration, width, height, size_bytes, master_playlist, thumbnail, source_bucket, source_key, error_message, created_at, updated_at FROM videos WHERE id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.MasterPlaylist,
		&i.Thumbnail,
		&i.SourceBucket,
		&i.SourceKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideoForUpdate = `-- name: GetVideoForUpdate :one
SELECT id, title, status, duration, width, height, size_bytes, master_playlist, thumbnail, source_bucket, source_key, error_message, created_at, updated_at FROM videos WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetVideoForUpdate(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoForUpdate, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.MasterPlaylist,
		&i.Thumbnail,
		&i.SourceBucket,
		&i.SourceKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVideos = `-- name: ListVideos :many
SELECT id, title, status, duration, width, height, size_bytes, master_playlist, thumbnail, source_bucket, source_key, error_message, created_at, updated_at FROM videos ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListVideosParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.MasterPlaylist,
			&i.Thumbnail,
			&i.SourceBucket,
			&i.SourceKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFailed = `-- name: MarkFailed :one
UPDATE videos
SET status = 'failed', error_message = $2
WHERE id = $1
RETURNING id, title, status, duration, width, height, size_bytes, master_playlist, thumbnail, source_bucket, source_key, error_message, created_at, updated_at
`

type MarkFailedParams struct {
	ID           uuid.UUID
	ErrorMessage *string
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) (Video, error) {
	row := q.db.QueryRow(ctx, markFailed, arg.ID, arg.ErrorMessage)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.MasterPlaylist,
		&i.Thumbnail,
		&i.SourceBucket,
		&i.SourceKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markProcessing = `-- name: MarkProcessing :one
UPDATE videos
SET status = 'processing'
WHERE id = $1
RETURNING id, title, status, duration, width, height, size_bytes, master_playlist, thumbnail, source_bucket, source_key, error_message, created_at, updated_at
`

func (q *Queries) MarkProcessing(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, markProcessing, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.MasterPlaylist,
		&i.Thumbnail,
		&i.SourceBucket,
		&i.SourceKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markProcessingFromUploading = `-- name: MarkProcessingFromUploading :one
UPDATE videos
SET status = 'processing'
WHERE id = $1 AND status = 'uploading'
RETURNING id, title, status, duration, width, height, size_bytes, master_playlist, thumbnail, source_bucket, source_key, error_message, created_at, updated_at
`

func (q *Queries) MarkProcessingFromUploading(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, markProcessingFromUploading, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.MasterPlaylist,
		&i.Thumbnail,
		&i.SourceBucket,
		&i.SourceKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markReady = `-- name: MarkReady :one
UPDATE videos
SET status = 'ready',
    duration = $2,
    width = $3,
    height = $4,
    size_bytes = $5,
    master_playlist = $6,
    thumbnail = $7,
    error_message = NULL
WHERE id = $1
RETURNING id, title, status, duration, width, height, size_bytes, master_playlist, thumbnail, source_bucket, source_key, error_message, created_at, updated_at
`

type MarkReadyParams struct {
	ID             uuid.UUID
	Duration       *float64
	Width          *int32
	Height         *int32
	SizeBytes      *int64
	MasterPlaylist *string
	Thumbnail      *string
}

func (q *Queries) MarkReady(ctx context.Context, arg MarkReadyParams) (Video, error) {
	row := q.db.QueryRow(ctx, markReady,
		arg.ID,
		arg.Duration,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.MasterPlaylist,
		arg.Thumbnail,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.MasterPlaylist,
		&i.Thumbnail,
		&i.SourceBucket,
		&i.SourceKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
